from __future__ import annotations

from typing import Protocol


class RadioPlayer(Protocol):
    def play(self, url: str) -> None: ...
    def pause(self) -> None: ...
    def resume(self) -> None: ...
    def stop(self) -> None: ...
    def toggle_pause(self) -> None: ...
    def set_volume(self, volume: int) -> None: ...
    def get_volume(self) -> int: ...
    def is_playing(self) -> bool: ...
    def is_alive(self) -> bool: ...
    def shutdown(self) -> None: ...
